### PR TITLE
Native http support

### PR DESCRIPTION
**Pull request by chindro**
these commits add functions that directly use the built-in HTTP functions of the SIM8/900 module, for now only HTTP GET is supported, maybe I will add POST in the future. 
Some of the commit messages are quite lengthy and provide some additional information.

### CODE REVIEW

**Comment by chindro** [comment]
are you going to merge it?

**Comment by lanselambor** [comment]
I failed to run the sample, do you know the reason? See below,
```
Initializing ...
OK
Check if network is registered...
Start HTTP demonstration, yeah!
if something is failing you may want to debug, check sim900.h

Initializing ...
OK
Check if network is registered...
OK
opening bearer ...
failed
```

**Comment by lanselambor** [comment]
@chindro I found three reasons caused the failure, 
- __openBearer__, sometimes we need to close bearer by AT+SAPBR=0,1 before sending AT+SAPBR=1,1
- __httpSendGetRequest__, the url content should not contain header __http://__
- httpReadResponseData, my net work is not so good, I need to wait for __10 seconds__ at least after sending __AT+HTTPACTOIN=0__

**Comment by lanselambor** [comment]
@chindro This pull request is nice, I will merge it first, and modified some code.

**Comment by chindro** [comment]
so, you will fix these issues the next days?

>     * **httpSendGetRequest**, the url content should not contain header **http://**
this is working for me. What device are you using? I'm using SIM800L.

**Comment by lanselambor** [comment]
@chindro I'm using SIM900, it's ok for containing header __http://__.
I saw that  if this sample were failed and return false,  __AT+HTTPINIT__ can only be executed once unless __AT+HTTPTERM__ were executed. The same situation for __AT+SAPBR=1,1__ and __AT+SAPBR=0,1__. 
I suggest before opening bearer we get bearer status then decide whether to open bearer or not. And before initializing http terminating http first.

**Pull request merged**
